export const calibrationCurveData = {

    'Melee Strength': {
        yLabel: 'Weight',
        maxValue: 1500,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}k` : `${val}`,
        note: 'Ceiling breakers: Apocalypse (score 15, ~500t) · Hulk (score 20, unlimited) · Gladiator (score 30, beyond unlimited)',
        points: [
            { score: 1,  value: 0.25, display: '500 lbs',   char: 'Nick Fury'  },
            { score: 2,  value: 0.5,  display: '1,000 lbs', char: 'Blk Widow'  },
            { score: 3,  value: 1,    display: '1 ton',     char: 'Cyclops'    },
            { score: 4,  value: 2,    display: '2 tons',    char: 'Cap'        },
            { score: 5,  value: 5,    display: '5 tons',    char: 'Sabretooth' },
            { score: 6,  value: 10,   display: '10 tons',   char: 'Beast'      },
            { score: 7,  value: 25,   display: '25 tons',   char: 'Spider-Man' },
            { score: 8,  value: 50,   display: '50 tons',   char: 'Rhino'      },
            { score: 9,  value: 75,   display: '75 tons',   char: 'Colossus'   },
            { score: 10, value: 100,  display: '100+ tons', char: 'Thor'       },
            { score: 15, value: 500,  display: '~500 tons', char: 'Apocalypse' },
            { score: 20, value: 1000, display: 'Unlimited', char: 'Hulk'       },
            { score: 30, value: 1500, display: '> Unlimited', char: 'Gladiator' },
        ],
    },

    'H2H Skill': {
        yLabel: 'Training Years (Equiv.)',
        maxValue: 1000,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}k` : `${val}`,
        note: 'Scale is 0–10 only — no ceiling breakers. Years represent equivalent mastery, not literal training time.',
        points: [
            { score: 1,  value: 2,    display: '~2 yrs',      char: null         },
            { score: 2,  value: 5,    display: '~5 yrs',      char: null         },
            { score: 3,  value: 10,   display: '~10 yrs',     char: 'Nick Fury'  },
            { score: 4,  value: 30,   display: '~30 yrs',     char: 'Cyclops'    },
            { score: 5,  value: 50,   display: '~50 yrs',     char: 'Blk Widow'  },
            { score: 6,  value: 100,   display: '~100 yrs',     char: 'Cap'        },
            { score: 7,  value: 200,  display: '~200 yrs',    char: 'Wolverine'  },
            { score: 8,  value: 400,  display: '~400 yrs',    char: null         },
            { score: 9,  value: 700,  display: '~700 yrs',     char: 'Thor'       },
            { score: 10, value: 1000, display: '~1,000 yrs',  char: 'Apocalypse' },
        ],
    },

    'Proj Power': {
        yLabel: 'TNT Equivalent',
        maxValue: 15000,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}kt` : `${val}t`,
        note: 'Score 10 = Hiroshima / Little Boy (~15 kt) · Curve decelerates through the nuclear tier',
        points: [
            { score: 1,  value: 0.2,   display: '~200 kg',  char: 'Nick Fury'  },
            { score: 2,  value: 1,     display: '~1 ton',   char: null         },
            { score: 3,  value: 5,     display: '~5 tons',  char: null         },
            { score: 4,  value: 22,    display: '~22 tons', char: 'Storm'      },
            { score: 5,  value: 90,    display: '~90 tons', char: null         },
            { score: 6,  value: 350,   display: '~350 tons', char: 'Iron Man'  },
            { score: 7,  value: 1200,  display: '~1.2 kt',  char: 'Magneto'   },
            { score: 8,  value: 3500,  display: '~3.5 kt',  char: 'Cyclops'   },
            { score: 9,  value: 8000,  display: '~8 kt',    char: 'Gladiator' },
            { score: 10, value: 15000, display: '~15 kt',   char: 'Apocalypse'},
        ],
    },

    'Proj Dist/Accuracy': {
        yLabel: 'Combat Range Score (CRS)',
        maxValue: 1000,
        formatGridLabel: (val) => val === 1000 ? '1k' : `${val}`,
        note: 'CRS is a composite index combining effective range and hit probability on a 0–1,000 scale',
        points: [
            { score: 1,  value: 10,   display: 'CRS 10',   char: null       },
            { score: 2,  value: 25,   display: 'CRS 25',   char: 'Cap'      },
            { score: 3,  value: 50,   display: 'CRS 50',   char: 'Spidey'   },
            { score: 4,  value: 100,  display: 'CRS 100',  char: null       },
            { score: 5,  value: 200,  display: 'CRS 200',  char: null       },
            { score: 6,  value: 350,  display: 'CRS 350',  char: null       },
            { score: 7,  value: 550,  display: 'CRS 550',  char: 'Storm'    },
            { score: 8,  value: 750,  display: 'CRS 750',  char: 'Iron Man' },
            { score: 9,  value: 900,  display: 'CRS 900',  char: 'Cyclops'  },
            { score: 10, value: 1000, display: 'CRS 1,000', char: null      },
        ],
    },

}
