export const calibrationCurveData = {

    'Melee Strength': {
        yLabel: 'Weight',
        maxValue: 1500,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}k` : `${val}`,
        note: 'Ceiling breakers: Apocalypse (score 15, ~500t) · Hulk (score 20, unlimited) · Gladiator (score 30, beyond unlimited)',
        points: [
            { score: 1,  value: 0.25, display: '500 lbs',   char: 'Nick Fury'  },
            { score: 2,  value: 0.5,  display: '1,000 lbs', char: 'Blk Widow'  },
            { score: 3,  value: 1,    display: '1 ton',     char: 'Cyclops'    },
            { score: 4,  value: 2,    display: '2 tons',    char: 'Cap'        },
            { score: 5,  value: 5,    display: '5 tons',    char: 'Sabretooth' },
            { score: 6,  value: 10,   display: '10 tons',   char: 'Beast'      },
            { score: 7,  value: 25,   display: '25 tons',   char: 'Spider-Man' },
            { score: 8,  value: 50,   display: '50 tons',   char: 'Rhino'      },
            { score: 9,  value: 75,   display: '75 tons',   char: 'Colossus'   },
            { score: 10, value: 100,  display: '100+ tons', char: 'Thor'       },
            { score: 15, value: 500,  display: '~500 tons', char: 'Apocalypse' },
            { score: 20, value: 1000, display: 'Unlimited', char: 'Hulk'       },
            { score: 30, value: 1500, display: '> Unlimited', char: 'Gladiator' },
        ],
    },

    'H2H Skill': {
        yLabel: 'Training Years (Equiv.)',
        maxValue: 1000,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}k` : `${val}`,
        note: 'Scale is 0–10 only — no ceiling breakers. Years represent equivalent mastery, not literal training time.',
        points: [
            { score: 1,  value: 2,    display: '~2 yrs',      char: null         },
            { score: 2,  value: 5,    display: '~5 yrs',      char: null         },
            { score: 3,  value: 10,   display: '~10 yrs',     char: 'Nick Fury'  },
            { score: 4,  value: 30,   display: '~30 yrs',     char: 'Cyclops'    },
            { score: 5,  value: 50,   display: '~50 yrs',     char: 'Blk Widow'  },
            { score: 6,  value: 100,   display: '~100 yrs',     char: 'Cap'        },
            { score: 7,  value: 200,  display: '~200 yrs',    char: 'Wolverine'  },
            { score: 8,  value: 400,  display: '~400 yrs',    char: null         },
            { score: 9,  value: 700,  display: '~700 yrs',     char: 'Thor'       },
            { score: 10, value: 1000, display: '~1,000 yrs',  char: 'Apocalypse' },
        ],
    },

    'Proj Power': {
        yLabel: 'TNT Equivalent',
        maxValue: 15000,
        formatGridLabel: (val) => val >= 1000 ? `${(val / 1000).toFixed(1).replace('.0', '')}kt` : `${val}t`,
        note: 'Score 10 = Hiroshima / Little Boy (~15 kt) · Curve decelerates through the nuclear tier',
        points: [
            { score: 1,  value: 0.2,   display: '~200 kg',  char: 'Nick Fury'  },
            { score: 2,  value: 1,     display: '~1 ton',   char: null         },
            { score: 3,  value: 5,     display: '~5 tons',  char: null         },
            { score: 4,  value: 22,    display: '~22 tons', char: 'Storm'      },
            { score: 5,  value: 90,    display: '~90 tons', char: null         },
            { score: 6,  value: 350,   display: '~350 tons', char: 'Iron Man'  },
            { score: 7,  value: 1200,  display: '~1.2 kt',  char: 'Magneto'   },
            { score: 8,  value: 3500,  display: '~3.5 kt',  char: 'Cyclops'   },
            { score: 9,  value: 8000,  display: '~8 kt',    char: 'Gladiator' },
            { score: 10, value: 15000, display: '~15 kt',   char: 'Apocalypse'},
        ],
    },

    'Proj Effective Range': {
        yLabel: 'Effective Range',
        maxValue: 52800,
        formatGridLabel: (val) => val >= 5280 ? `${(val / 5280).toFixed(1).replace('.0', '')} mi` : `${val} ft`,
        note: 'Y-axis shows maximum effective range — accuracy is baked into the score, not charted separately',
        points: [
            { score: 1,  value: 20,    display: '~20 ft',  char: 'Hulk'     },
            { score: 2,  value: 50,    display: '~50 ft',  char: null        },
            { score: 3,  value: 100,   display: '~100 ft', char: 'Spider-Man' },
            { score: 4,  value: 300,   display: '~300 ft', char: 'Nick Fury'  },
            { score: 5,  value: 500,   display: '~500 ft', char: 'Thor'       },
            { score: 6,  value: 1000,  display: '~1k ft',  char: 'Magneto'    },
            { score: 7,  value: 5280,  display: '~1 mi',   char: 'Apocalypse' },
            { score: 8,  value: 15840, display: '~3 mi',   char: 'Gladiator'  },
            { score: 9,  value: 26400, display: '~5 mi',   char: 'Iron Man'  },
            { score: 10, value: 52800, display: '~10 mi',  char: 'Cyclops'   },
        ],
    },

    'Healing': {
        yLabel: 'Healing Factor',
        maxValue: 225,
        formatGridLabel: (val) => `${val}×`,
        note: 'Perfect parabola: y = score² · Score 1 = healthy human · Score 2 = baseline mutant · Score 10 = Hulk (standard ceiling) · Score 9 = Wolverine · Score 8 = Sabretooth · Ceiling breaker: Apocalypse (score 15, 225×) — near-instant molecular reconstruction',
        points: [
            { score: 1,  value: 1,   display: '1×',   char: 'Nick Fury'  },
            { score: 2,  value: 4,   display: '4×',   char: 'Cyclops'    },
            { score: 3,  value: 9,   display: '9×',   char: 'Cap'        },
            { score: 4,  value: 16,  display: '16×',  char: 'Beast'      },
            { score: 5,  value: 25,  display: '25×',  char: 'Thor'       },
            { score: 6,  value: 36,  display: '36×',  char: null         },
            { score: 7,  value: 49,  display: '49×',  char: null         },
            { score: 8,  value: 64,  display: '64×',  char: 'Sabretooth' },
            { score: 9,  value: 81,  display: '81×',  char: 'Wolverine'  },
            { score: 10, value: 100, display: '100×', char: 'Hulk'       },
            { score: 15, value: 225, display: '225×', char: 'Apocalypse' },
        ],
    },

    'Armor': {
        yLabel: 'Protective Factor',
        maxValue: 100,
        formatGridLabel: (val) => `${val}x`,
        note: 'Perfect parabola: y = score² · Measures inherent body/power durability only — removable gear excluded · Score 10 = survives direct Thor/Hulk-tier hits; only telepathy or specific magic bypasses it',
        points: [
            { score: 1,  value: 1,   display: '1×',   char: 'Nick Fury'  },
            { score: 2,  value: 4,   display: '4×',   char: 'Cyclops'    },
            { score: 3,  value: 9,   display: '9×',   char: 'Cap'        },
            { score: 4,  value: 16,  display: '16×',  char: 'Beast'      },
            { score: 5,  value: 25,  display: '25×',  char: 'Sabretooth' },
            { score: 6,  value: 36,  display: '36×',  char: null         },
            { score: 7,  value: 49,  display: '49×',  char: 'Wolverine'  },
            { score: 8,  value: 64,  display: '64×',  char: 'Apocalypse' },
            { score: 9,  value: 81,  display: '81×',  char: 'Thor'       },
            { score: 10, value: 100, display: '100×', char: 'Juggernaut' },
        ],
    },

    'Quickness': {
        yLabel: 'Atk / Second',
        maxValue: 20,
        formatGridLabel: (val) => `${val}/sec`,
        note: 'Physical strikes only (punches, kicks, claws) — energy attack frequency is Proj Power · Ceiling breaker: Quicksilver (score 50, 500+/sec) — excluded from graph · Score 0 = teleportation characters (mutually exclusive)',
        points: [
            { score: 1,  value: 1,  display: '1/sec',   char: 'Juggernaut' },
            { score: 2,  value: 2,  display: '~2/sec',  char: 'Nick Fury'  },
            { score: 3,  value: 3,  display: '~3/sec',  char: 'Cyclops'    },
            { score: 4,  value: 5,  display: '~5/sec',  char: 'Blk Widow'  },
            { score: 5,  value: 7,  display: '~7/sec',  char: 'Cap'        },
            { score: 6,  value: 9,  display: '~9/sec',  char: 'Beast'      },
            { score: 7,  value: 12, display: '~12/sec', char: 'Sabretooth' },
            { score: 8,  value: 15, display: '~15/sec', char: 'Spider-Man' },
            { score: 9,  value: 18, display: '~18/sec', char: 'Thor'       },
            { score: 10, value: 20, display: '~20/sec', char: 'Gladiator'  },
        ],
    },

}
