export const characters = [
  {
    "Character": "Hulk",
    "Melee Strength": 20,
    "H2H Skill": 3,
    "Proj Power": 5,
    "Proj Dist/Accuracy": 3,
    "Armor": 10,
    "Healing": 10,
    "Quickness": 7,
    "Flight Spd": 0,
    "Hunting/Tracking": 2,
    "Leadership": 1,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 4,
    "Magnetism": 0,
    "Has Metal": 2,
    "Magic Cast": 0,
    "Magic Resist": 5,
    "Absorption": 8,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 6,
    "Sky Manip": 1
  },
  {
    "Character": "Captain America",
    "Melee Strength": 4,
    "H2H Skill": 5,
    "Proj Power": 2,
    "Proj Dist/Accuracy": 2,
    "Armor": 4,
    "Healing": 3,
    "Quickness": 6,
    "Flight Spd": 0,
    "Hunting/Tracking": 6,
    "Leadership": 10,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 6,
    "Magnetism": 0,
    "Has Metal": 1,
    "Magic Cast": 0,
    "Magic Resist": 2,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0
  },
  {
    "Character": "Iron Man",
    "Melee Strength": 5,
    "H2H Skill": 4,
    "Proj Power": 10,
    "Proj Dist/Accuracy": 9,
    "Armor": 7,
    "Healing": 3,
    "Quickness": 7,
    "Flight Spd": 0,
    "Hunting/Tracking": 3,
    "Leadership": 6,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 7,
    "Magnetism": 2,
    "Has Metal": 1,
    "Magic Cast": 0,
    "Magic Resist": 3,
    "Absorption": 5,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 6,
    "Sky Manip": 1
  },
  {
    "name": "Storm",
    "Melee Strength": 2,
    "H2H Skill": 3,
    "Proj Power": 6,
    "Proj Dist/Acuracy": 7,
    "Armor": 3,
    "Healing": 3,
    "Quickness": 5,
    "Flight Spd": 7,
    "Hunting/Tracking": 6,
    "Leadership": 8,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 4,
    "Magnetism": 0,
    "Has Metal": 1,
    "Magic Cast": 0,
    "Magic Resist": 3,
    "Absorption": 0,
    "Water Manipulation": 4,
    "Cold Manipulation": 5,
    "Heat Manipulation": 3,
    "Sky Manipulation": 9
  },
  {
    "Character": "Spider-Man",
    "Melee Strength": 6,
    "H2H Skill": 6,
    "Proj Power": 4,
    "Proj Dist/Accuracy": 5,
    "Armor": 3,
    "Healing": 6,
    "Quickness": 9,
    "Flight Spd": 0,
    "Hunting/Tracking": 4,
    "Leadership": 5,
    "Telekinesis": 0,
    "Telepathy": 1,
    "Telepath Resist": 5,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 3,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0
  },
  {
    "Character": "Black Widow",
    "Melee Strength": 2,
    "H2H Skill": 6,
    "Proj Power": 2,
    "Proj Dist/Accuracy": 4,
    "Armor": 2,
    "Healing": 3,
    "Quickness": 7,
    "Flight Spd": 0,
    "Hunting/Tracking": 5,
    "Leadership": 6,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 3,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 2,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0
  },
  {
    "name": "Magneto",
    "Melee Strength": 3,
    "H2H Skill": 4,
    "Proj Power": 8,
    "Proj Dist/Acuracy": 8,
    "Armor": 6,
    "Healing": 4,
    "Quickness": 5,
    "Flight Spd": 6,
    "Hunting/Tracking": 5,
    "Leadership": 7,
    "Telekinesis": 4,
    "Telepathy": 0,
    "Telepath Resist": 7,
    "Magnetism": 10,
    "Has Metal": 8,
    "Magic Cast": 0,
    "Magic Resist": 4,
    "Absorption": 2,
    "Water Manipulation": 0,
    "Cold Manipulation": 0,
    "Heat Manipulation": 0,
    "Sky Manipulation": 3
  }
]