export const characters = [
  {
    "Character": "Nick Fury",
    "Melee Strength": 1,
    "H2H Skill": 3,
    "Proj Power": 1,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Black Widow",
    "Melee Strength": 2,
    "H2H Skill": 5,
    "Proj Power": 1,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Storm",
    "Melee Strength": 2,
    "H2H Skill": 3,
    "Proj Power": 4,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Cyclops",
    "Melee Strength": 3,
    "H2H Skill": 4,
    "Proj Power": 8,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Magneto",
    "Melee Strength": 3,
    "H2H Skill": 2,
    "Proj Power": 7,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Captain America",
    "Melee Strength": 4,
    "H2H Skill": 6,
    "Proj Power": 1,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Wolverine",
    "Melee Strength": 4,
    "H2H Skill": 7,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Sabretooth",
    "Melee Strength": 5,
    "H2H Skill": 7,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Beast",
    "Melee Strength": 6,
    "H2H Skill": 5,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Spider-Man",
    "Melee Strength": 7,
    "H2H Skill": 6,
    "Proj Power": 1,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Rhino",
    "Melee Strength": 8,
    "H2H Skill": 1,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Colossus",
    "Melee Strength": 9,
    "H2H Skill": 3,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Iron Man",
    "Melee Strength": 9,
    "H2H Skill": 2,
    "Proj Power": 6,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Thor",
    "Melee Strength": 10,
    "H2H Skill": 9,
    "Proj Power": 6,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Juggernaut",
    "Melee Strength": 10,
    "H2H Skill": 1,
    "Proj Power": 0,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Apocalypse",
    "Melee Strength": 15,
    "H2H Skill": 10,
    "Proj Power": 10,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Hulk",
    "Melee Strength": 20,
    "H2H Skill": 1,
    "Proj Power": 1,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  },
  {
    "Character": "Gladiator",
    "Melee Strength": 30,
    "H2H Skill": 10,
    "Proj Power": 9,
    "Proj Dist/Accuracy": 0,
    "Armor": 0,
    "Healing": 0,
    "Quickness": 0,
    "Flight Spd": 0,
    "Hunting/Tracking": 0,
    "Leadership": 0,
    "Telekinesis": 0,
    "Telepathy": 0,
    "Telepath Resist": 0,
    "Magnetism": 0,
    "Has Metal": 0,
    "Magic Cast": 0,
    "Magic Resist": 0,
    "Absorption": 0,
    "Water Manip": 0,
    "Cold Manip": 0,
    "Heat Manip": 0,
    "Sky Manip": 0,
    "Stealth/Deception": 0,
    "Teleportation": 0,
    "Shield": 0
  }
]
